on:
  release:
    types: [created]

jobs:
  release:
    name: release plugin wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          RUSTTARGET: wasm32-wasi
